#ifndef __FFI_H__
#define __FFI_H__

/* Generated with cbindgen:0.14.1 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
namespace energonsoftware {
#endif // __cplusplus

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

int32_t compute_value_a(int32_t x, int32_t y);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus

#ifdef __cplusplus
} // namespace energonsoftware
#endif // __cplusplus

#endif /* __FFI_H__ */
