#ifndef __FFI_H__
#define __FFI_H__

/* Generated with cbindgen:0.14.1 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
namespace energonsoftware {
#endif // __cplusplus

typedef struct {
  int64_t x;
  int64_t y;
  int64_t z;
} InputValues;

typedef struct {
  int64_t x;
  int64_t y;
  int64_t z;
} OutputValues;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

char *InputValues_to_string(const InputValues *this_);

char *OutputValues_to_string(const OutputValues *this_);

OutputValues compute_values(const InputValues *input, int64_t scale);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus

#ifdef __cplusplus
} // namespace energonsoftware
#endif // __cplusplus

#endif /* __FFI_H__ */
